create/urls.py
# create urls

from django.urls import path

from . import views

app_name = 'create'
urlpatterns = [
    path('', views.home, name='home'),
    path('my_documents', views.my_documents, name='my_documents'),
    path('create_bill_of_sale/', views.create_bill_of_sale, name='create_bill_of_sale'),
    path('create_bill_of_sale/<int:page>/', views.create_bill_of_sale, name='create_bill_of_sale'),
    path('create_bill_of_sale/<int:page>/<int:id>/', views.create_bill_of_sale, name='create_bill_of_sale'),
    path('view_bill_of_sale/', views.view_bill_of_sale, name='view_bill_of_sale'),
    path('view_bill_of_sale/<int:id>/', views.view_bill_of_sale, name='view_bill_of_sale'),
    path('view_bill_of_sale_pdf/', views.view_bill_of_sale_pdf, name='view_bill_of_sale_pdf'),
    path('view_bill_of_sale_pdf/<int:id>/', views.view_bill_of_sale_pdf, name='view_bill_of_sale_pdf'),
]

fastform/create/urls.py
# create urls

from django.urls import path

from . import views, user_views

app_name = 'create'
urlpatterns = [
    path('', views.home, name='home'),
    path('sign_up', user_views.sign_up, name='sign_up'),
    path('sign_up/<int:id>', user_views.sign_up, name='sign_up'),
    path('log_in', user_views.log_in, name='log_in'),
    path('log_in/<int:id>', user_views.log_in, name='log_in'),
    path('log_out', user_views.log_out, name='log_out'),
    path('my_documents', views.my_documents, name='my_documents'),
    path('create_document/<int:id>/', views.create_document, name='create_document'),
    path('create_bill_of_sale/', views.create_bill_of_sale, name='create_bill_of_sale'),
    path('create_bill_of_sale/<int:page>/', views.create_bill_of_sale, name='create_bill_of_sale'),
    path('create_bill_of_sale/<int:page>/<int:id>/', views.create_bill_of_sale, name='create_bill_of_sale'),
    path('view_document/<int:id>/', views.view_document, name='view_document'),
    path('view_bill_of_sale/', views.view_bill_of_sale, name='view_bill_of_sale'),
    path('view_bill_of_sale/<int:id>/', views.view_bill_of_sale, name='view_bill_of_sale'),
    path('view_pdf_document/<int:id>/', views.view_pdf_document, name='view_pdf_document'),
    path('view_pdf_bill_of_sale/', views.view_pdf_bill_of_sale, name='view_pdf_bill_of_sale'),
    path('view_pdf_bill_of_sale/<int:id>/', views.view_pdf_bill_of_sale, name='view_pdf_bill_of_sale'),
    path('delete_document/<int:id>/', views.delete_document, name='delete_document'),
]

fastform/urls.py
# Main urls
"""fastform URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('index.urls'), name='index'),
    path('create/', include('create.urls'), name='create'),
]

index/urls.py
# Index urls

from django.urls import path

from . import views

app_name = 'index'
urlpatterns = [
    path('', views.home, name='home'),
]

create/models.py
import datetime

from django.db import models
from django.utils import timezone


# Create your models here.
DOCUMENT_TYPES = (('', 'empty'), ('bill_of_sale', 'Bill of Sale'), ('articles_of_incorporation', 'Articles of Incorporation')) 

class Document(models.Model):
    doc_id = models.PositiveBigIntegerField("Document ID", default=0)
    doc_type = models.CharField("Document Type", max_length=200, blank=True, choices=DOCUMENT_TYPES, default='')
    # Document name should be Document01, 02 ... (need additional function)
    doc_name = models.CharField(max_length=20, default="Document name")
    doc_date = models.DateTimeField(default=timezone.now)

    
STATES =  (('', '- State -'), ('AL', 'Alabama'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'))

class BillOfSale(models.Model):
    # Document name should be Document01, 02 ... (need additional function)
    document_name = models.CharField(max_length=20, default="Document name")
    document_date = models.DateTimeField(default=timezone.now)

    seller_name = models.CharField('Name', max_length=200, blank=True)
    seller_address = models.CharField('Address', max_length=200, blank=True)
    seller_city = models.CharField('City', max_length=200, blank=True)
    seller_state = models.CharField("State", max_length=200, blank=True, choices=STATES, default='')
    seller_zip = models.CharField('Zip', max_length=200, blank=True)

    buyer_name = models.CharField('Name', max_length=200, blank=True)
    buyer_address = models.CharField('Address', max_length=200, blank=True)
    buyer_city = models.CharField('City', max_length=200, blank=True)
    buyer_state = models.CharField('State', max_length=200, blank=True, choices=STATES, default='')
    buyer_zip = models.CharField('Zip', max_length=5, blank=True)

    properties = models.CharField(max_length=200, blank=True)
    price = models.CharField(max_length=20, blank=True)
    sale_date = models.DateField(default=timezone.now)


    def save(self, *args, **kwargs):
        new = False
        if not self.pk:  # object is being created, thus no primary key field yet
            new = True
            
        super(BillOfSale, self).save(*args, **kwargs)
        if new:
            document = Document.objects.create()
            document.doc_id = self.id
            document.doc_type = 'bill_of_sale'
            document.doc_name = self.document_name
            document.save()

    # def __str__(self):
    #     return 

create/forms.py
from django import forms
from django.forms import ModelForm, CharField
from .models import BillOfSale
from django.utils import timezone

class BillOfSaleForm(ModelForm):
    class Meta:
        model = BillOfSale
        fields = ['seller_name', 'seller_address', 'seller_city',
        'seller_state', 'seller_zip', 'buyer_name', 'buyer_address', 'buyer_city', 'buyer_state',
        'buyer_zip', 'properties', 'price', 'sale_date']


class BillOfSaleForm01(ModelForm):
    class Meta:
        model = BillOfSale
        fields = ['seller_name', 'seller_address', 'seller_city',
        'seller_state', 'seller_zip']


class BillOfSaleForm02(ModelForm):
    class Meta:
        model = BillOfSale
        fields = ['buyer_name', 'buyer_address', 'buyer_city',
        'buyer_state', 'buyer_zip']


class BillOfSaleForm03(ModelForm):
    class Meta:
        model = BillOfSale
        fields = ['properties', 'price', 'sale_date']

    

create/views.py
from django.shortcuts import render, redirect, get_object_or_404, Http404

from django.http import HttpResponse
from django.template import loader
from django.views.decorators.clickjacking import xframe_options_sameorigin
from django.utils import timezone

from .models import BillOfSale, Document
from .forms import BillOfSaleForm, BillOfSaleForm01, BillOfSaleForm02, BillOfSaleForm03

# Create your views here.
def home(request):
    return render(request, 'create/home.html', {})


def my_documents(request):
    documents = Document.objects.all()
    return render(request, 'create/my_documents.html', {'documents': documents})


def create_bill_of_sale(request, page=None, id=None):
    instance = get_object_or_404(BillOfSale, id=id) if id else None
    next_page = 0
    if request.method == "POST":
        if page is None or page == 1:
            page = 1
            form = BillOfSaleForm01(request.POST, instance=instance)
            next_page = 2
        elif page == 2 and id:
            form = BillOfSaleForm02(request.POST, instance=instance)
            next_page = 3
        elif page == 3 and id:
            form = BillOfSaleForm03(request.POST, instance=instance)
        else:
            print("****PAGE ", page)
            raise Http404("Page does not exist")

        if form.is_valid():
            bill_of_sale = form.save()
            id = bill_of_sale.id   
        else:
            print('not valid')
            print(form.errors)
        if page == 3:    
            return redirect('create:view_bill_of_sale', id=id)    
            # return redirect('index:home')    
        return redirect('create:create_bill_of_sale', page=next_page, id=id)
    
    else:
        title = {1: "Who is the Seller?", 2: "Who is the Buyer?", 3: "What is the Property?"}
        if page is None or page == 1:
            page = 1
            form = BillOfSaleForm01(instance=instance)
        elif page == 2 and id:
            form = BillOfSaleForm02(instance=instance)
        elif page == 3 and id:
            form = BillOfSaleForm03(instance=instance)
        else:
            raise Http404("Page does not exist")
    context = {'form': form, 'page': page, "id" : id, "title" : title[page]}
    return render(request, 'create/build_bill_of_sale_01.html', context)


@xframe_options_sameorigin
def view_bill_of_sale(request, id=None):
    bill_of_sale = get_object_or_404(BillOfSale, id = id) if id else None
    template = loader.get_template('create/bill_of_sale.html')
    context = {'bill_of_sale': bill_of_sale}

    return HttpResponse(template.render(context, request))


from io import BytesIO
from django.http import HttpResponse
from django.template.loader import get_template
import xhtml2pdf.pisa as pisa

def view_bill_of_sale_pdf(request, id=None):
    bill_of_sale = get_object_or_404(BillOfSale, id = id) if id else 0
    template = loader.get_template('create/bill_of_sale_pdf.html')
    context = {'bill_of_sale': bill_of_sale}
    html = template.render(context, request)
    
    response = BytesIO()
    pdf = pisa.pisaDocument(BytesIO(html.encode("UTF-8")), response)
    if not pdf.err:
        return HttpResponse(response.getvalue(), content_type='application/pdf')
    else:
        return HttpResponse("Error Rendering PDF", status=400)

fastform/create/views.py
from django.shortcuts import render, redirect, get_object_or_404, Http404

from django.http import HttpResponse
from django.template import loader
from django.views.decorators.clickjacking import xframe_options_sameorigin
from django.utils import timezone

from .models import BillOfSale, Document
from .forms import BillOfSaleForm, BillOfSaleForm01, BillOfSaleForm02, BillOfSaleForm03

# Create your views here.
def home(request):
    return render(request, 'create/home.html', {})

def my_documents(request):
    if request.user.is_authenticated:
        user = request.user
    else:
        return redirect('create:log_in')

    documents = Document.objects.filter(user=user)
    return render(request, 'create/my_documents.html', {'documents': documents})

def create_document(request, id):
    document = get_object_or_404(Document, id=id)
    address = 'create:create_' + document.doc_type
    return redirect(address, page=1, id=document.doc_id)   

def create_bill_of_sale(request, page=None, id=None):
    instance = get_object_or_404(BillOfSale, id=id) if id else None
    next_page = 0
    if request.user.is_authenticated:
        user = request.user
    else:
        user = None
    if instance and instance.user != user:
        return redirect('create:my_documents')

    if request.method == "POST":
        if page is None or page == 1:
            page = 1
            form = BillOfSaleForm01(request.POST, instance=instance)
            next_page = 2
        elif page == 2 and id:
            form = BillOfSaleForm02(request.POST, instance=instance)
            next_page = 3
        elif page == 3 and id:
            form = BillOfSaleForm03(request.POST, instance=instance)
        else:
            print("****PAGE ", page)
            raise Http404("Page does not exist")

        if form.is_valid():
            bill_of_sale = form.save()
            id = bill_of_sale.id   
            if not instance:
                bill_of_sale.user = user
                bill_of_sale.save()
            
        else:
            print('not valid')
            print(form.errors)
        if page == 3:
            if user:    
                return redirect('create:my_documents')
            else:
                return redirect('create:log_in', id=bill_of_sale.document.id)
            # return redirect('index:home')    
        return redirect('create:create_bill_of_sale', page=next_page, id=id)
    
    else:
        title = {1: "Who is the Seller?", 2: "Who is the Buyer?", 3: "What is the Property?"}
        if page is None or page == 1:
            page = 1
            form = BillOfSaleForm01(instance=instance)
        elif page == 2 and id:
            form = BillOfSaleForm02(instance=instance)
        elif page == 3 and id:
            form = BillOfSaleForm03(instance=instance)
        else:
            raise Http404("Page does not exist")
    context = {'form': form, 'page': page, "id" : id, "title" : title[page]}
    return render(request, 'create/build_bill_of_sale_01.html', context)

def view_document(request, id):
    document = get_object_or_404(Document, id=id)
    address = 'create:view_' + document.doc_type
    return redirect(address, id=document.doc_id)   


@xframe_options_sameorigin
def view_bill_of_sale(request, id=None):
    bill_of_sale = get_object_or_404(BillOfSale, id = id) if id else None
    template = loader.get_template('create/bill_of_sale.html')
    context = {'bill_of_sale': bill_of_sale}

    return HttpResponse(template.render(context, request))


def view_pdf_document(request, id):
    document = get_object_or_404(Document, id=id)
    address = 'create:view_pdf_' + document.doc_type
    return redirect(address, id=document.doc_id)   


from io import BytesIO
from django.http import HttpResponse
from django.template.loader import get_template
import xhtml2pdf.pisa as pisa

def view_pdf_bill_of_sale(request, id=None):
    bill_of_sale = get_object_or_404(BillOfSale, id = id) if id else 0
    template = loader.get_template('create/bill_of_sale_pdf.html')
    context = {'bill_of_sale': bill_of_sale}
    html = template.render(context, request)
    
    response = BytesIO()
    pdf = pisa.pisaDocument(BytesIO(html.encode("UTF-8")), response)
    if not pdf.err:
        return HttpResponse(response.getvalue(), content_type='application/pdf')
    else:
        return HttpResponse("Error Rendering PDF", status=400)

document_models = {"bill_of_sale": BillOfSale}
def delete_document(request, id):
    document = get_object_or_404(Document, id=id)
    document_child = get_object_or_404(document_models[document.doc_type], id=document.doc_id)
    document_child.delete()
    document.delete()
    return redirect('create:my_documents')

fastform/create/templates/create/footer.html
<!-- Footer -->
<footer id="footer">
    <ul class="icons">
        <li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
        <li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
        <li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
    </ul>
    <div class="copyright">
        &copy; FastForm: <a href="{% url 'create:home' %}">Make Forms Fast</a>
        <br>Design: <a href="https://github.com/csc5nz">CSC</a>
    </div>
</footer>

fastform/create/templates/create/header.html
<!-- Header -->
<header id="header">
    <a href="{% url 'create:home' %}" class="logo"><strong>FastForm</strong></a>
    <nav>
        <a href="#menu">Menu</a>
    </nav>
</header>

fastform/create/templates/create/home.html
{% load static %}

<!DOCTYPE HTML>

<html>
	<head>
		<title>FastForm - Create your form</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" type="text/css" href="{% static 'create/assets/css/main.css'%}" />
	</head>
	<body>

		{% include "create/header.html" %}

		{% include "create/nav.html" %}

		<!-- Main -->
			<section id="main">
				<div class="inner">
					<header class="major special">
						<h1>Free Legal Documents</h1>
						<p>A tool from the document experts at FastForm</p>
					</header>

					<!-- Text -->
						<section>
							
							<header>
								
								<h2>Financial</h2>
							</header>

							<header>
								<a href="{% url 'create:create_bill_of_sale'  %}" class="logo"><h4>Bill Of Sale</h4></a>
							</header>
							<p>Nunc lacinia ante nunc ac lobortis. Interdum adipiscing gravida odio porttitor sem non mi integer non faucibus ornare mi ut ante amet placerat aliquet. Volutpat eu sed ante lacinia sapien lorem accumsan varius montes viverra nibh in adipiscing blandit tempus accumsan.
								<ul class="actions">
									<li><a href="{% url 'create:create_bill_of_sale' %}" class="button special">Create New</a></li>
									<li><a href="#" class="button icon fa-download">Download Word File</a></li>
									<li><a href="{% url 'create:view_pdf_bill_of_sale' %}" class="button icon fa-download">Download PDF</a></li>
								</ul>
							</p>
							
							<header>
								<h4>Cease And Desist Breach Of Contract Letter</h4>
							</header>
							<p>Nunc lacinia ante nunc ac lobortis. Interdum adipiscing gravida odio porttitor sem non mi integer non faucibus ornare mi ut ante amet placerat aliquet. Volutpat eu sed ante lacinia sapien lorem accumsan varius montes viverra nibh in adipiscing blandit tempus accumsan.
								<ul class="actions">
									<li><a href="#" class="button special">Edit PDF</a></li>
									<li><a href="#" class="button">Download Word File</a></li>
									<li><a href="#" class="button alt">Download PDF</a></li>
								</ul>
							</p>
							
							<hr />

							<h2>Bussiness</h2>
						</header>

						<header>
							<h4>Articles Of Incorporation</h4>
						</header>
						<p>Nunc lacinia ante nunc ac lobortis. Interdum adipiscing gravida odio porttitor sem non mi integer non faucibus ornare mi ut ante amet placerat aliquet. Volutpat eu sed ante lacinia sapien lorem accumsan varius montes viverra nibh in adipiscing blandit tempus accumsan.</p>
						
						<header>
							<h4>Bill Of Lading</h4>
						</header>
						<p>Nunc lacinia ante nunc ac lobortis. Interdum adipiscing gravida odio porttitor sem non mi integer non faucibus ornare mi ut ante amet placerat aliquet. Volutpat eu sed ante lacinia sapien lorem accumsan varius montes viverra nibh in adipiscing blandit tempus accumsan.</p>
						
						<hr />

				</div>
			</section>

		{% include "create/footer.html" %}

		<!-- Scripts -->
			<!-- Scripts -->
			<script src="{% static 'create/assets/js/jquery.min.js' %}"></script>
			<script src="{% static 'create/assets/js/jquery.scrolly.min.js' %}"></script>
			<script src="{% static 'create/assets/js/skel.min.js' %}"></script>
			<script src="{% static 'create/assets/js/util.js' %}"></script>
			<script src="{% static 'create/assets/js/main.js' %}"></script>
		

	</body>
</html>

fastform/create/templates/create/log_in.html
{% load static %}
<!DOCTYPE HTML>

<html>
	<head>
		<title>FastForm - Create your form</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" type="text/css" href="{% static 'create/assets/css/main.css'%}" />
	</head>
	<body>

		{% include "create/header.html" %}

		{% include "create/nav.html" %}

		<!-- Main -->
			<section id="main">
				<div class="inner 3u 6u$">
					
					<!-- Form -->
						<section>
							<h2>Log In</h2>
							<form method="POST" action="#">
								{% csrf_token %}
								<div class="row uniform 50%">
									{% for field in form %}
									<div class="12u$">
										{{ field.label }}
										{{ field }}
										{{ field.errors}}
									</div>
									{% endfor %}
								
									<div class="12u$">
										<ul class="actions">
											<li><input type="submit" value="Log In" class="special" /></li>
											<!-- <li><input type="reset" value="Cancel" /></li> -->
										</ul>
										<ul class="actions">
											{% if document %}
												<li><a href="{% url 'create:sign_up' id=document.id %}">Sign Up</a></li>
											{% else %}
												<li><a href="{% url 'create:sign_up'%}">Sign Up</a></li>
											{% endif %}
										</ul>
									</div>
								</div>
							</form>
						</section>

					

				</div>
			</section>

		{% include "create/footer.html" %}

		<!-- Scripts -->
		<script src="{% static 'create/assets/js/jquery.min.js' %}"></script>
		<script src="{% static 'create/assets/js/jquery.scrolly.min.js' %}"></script>
		<script src="{% static 'create/assets/js/skel.min.js' %}"></script>
		<script src="{% static 'create/assets/js/util.js' %}"></script>
		<script src="{% static 'create/assets/js/main.js' %}"></script>
	
	</body>
</html>

fastform/create/templates/create/my_documents.html
{% load static %}

<!DOCTYPE HTML>

<html>
	<head>
		<title>FastForm - Create your form</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" type="text/css" href="{% static 'create/assets/css/main.css'%}" />
	</head>
	<body>

		{% include "create/header.html" %}

		{% include "create/nav.html" %}

		<!-- Main -->
			<section id="main">
				<div class="inner">
					<header class="major special">
						<h1>Recent Documents</h1>
					</header>

						<section>
							<div class="table-wrapper">
								<table class="alt">
									<thead>
										<tr>
											<th>Document</th>
											<th>Date</th>
											<th>Actions</th>
										</tr>
									</thead>

									<tbody>
										
										{% for document in documents %}
										<tr>
											
											<td><a href="{% url 'create:create_document' id=document.id %}">{{ document.doc_name }}</a></td>
											
											<td>{{ document.doc_date }}</td>
											<td>
											
												<ul class="actions small">
												<li><a href="#" class="button special small icon fa-print">Print</a></li>
												<li><a href="{% url 'create:view_pdf_document' id=document.id %}" class="button alt small icon fa-download">Download PDF</a></li>
												<li><a href="#" class="button alt small icon fa-envelope">Send PDF</a></li>
												</ul>
												
											 </td>
											<td><a href="{% url 'create:delete_document' id=document.id %}" class="button special small icon fa-trash">Delete</a></td>
										
										</tr>
										{% empty  %}
										<tr>
											<td>No documents </td>
											<td> </td>
											<td> </td>
											<td> </td>
										</tr>
										{% endfor %}	
										
									</tbody>
									<tfoot>
										<tr>
											<td colspan="3"></td>
											<td>Page 1 of 1</td>
										</tr>
									</tfoot>
								</table>
							</section>
								

							<!-- Lists -->
						<section>
							<!-- <h3>Lists</h3> -->
							<div class="row">
								<div class="6u 12u$(xsmall)">

									<h3>Create a New Document</h3>
									<ul class="actions">
										<li><input type="text" name="name" id="name" value="" placeholder="What are you looking for?" /></li>
										<li><a href="#" class="button special icon fa-search">Search</a></li>
										
									</ul>

									
									<h4>Suggested For You</h4>
									<ul class="alt">
										<li><a href="{% url 'create:create_bill_of_sale' %}">Bill of Sale</a></li>
										<li><a href="#">Articles Of Incorporation</a></li>
										<li><a href="#">Cease And Desist Breach Of Contract Letter</a></li>
									</ul>

								</div>
								<div class="6u$ 12u$(xsmall)">

									<h3>Upload a Document to Edit</h3>
									<ul class="actions vertical">
										<li><input type="radio" id="priority-low" name="priority" checked>
											<label for="priority-low">I want to edit PDF only</label></li>
										<li><input type="radio" id="priority-low" name="priority">
											<label for="priority-low">I want to edit my PDF & rearrange pages</label></li>
										<li><li><a href="#" class="button special icon fa-upload">Select a Document to Upload</a></li></li>
										
									</ul>

									
							</div>
						</section>

								


					</div>
				</section>
						


						
					

		{% include "create/footer.html" %}

		<!-- Scripts -->
		<script src="{% static 'create/assets/js/jquery.min.js' %}"></script>
		<script src="{% static 'create/assets/js/jquery.scrolly.min.js' %}"></script>
		<script src="{% static 'create/assets/js/skel.min.js' %}"></script>
		<script src="{% static 'create/assets/js/util.js' %}"></script>
		<script src="{% static 'create/assets/js/main.js' %}"></script>
	
	</body>
</html>

fastform/create/templates/create/nav.html
<!-- Nav -->
<nav id="menu">
    <ul class="links">
        <li><a href="{% url 'create:home' %}">Home</a></li>
        <li><a href="{% url 'create:my_documents' %}">My Account</a></li>
        {% if user.is_authenticated %}
        <li><a href="{% url 'create:log_out' %}">Log Out</a></li>
        {% else %}
        <li><a href="{% url 'create:log_in' %}">Log In</a></li>
        {% endif %}
    </ul>
</nav>

fastform/create/templates/create/sign_up.html
{% load static %}
<!DOCTYPE HTML>

<html>
	<head>
		<title>FastForm - Create your form</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" type="text/css" href="{% static 'create/assets/css/main.css'%}" />
	</head>
	<body>

		{% include "create/header.html" %}

		{% include "create/nav.html" %}

		<!-- Main -->
			<section id="main">
				<div class="inner 3u 6u$">
					
					<!-- Form -->
						<section>
							<h2>Sign Up</h2>
							<form method="POST" action="#">
								{% csrf_token %}
								<div class="row uniform 50%">
									{% for field in form %}
									<div class="12u$">
										{{ field.label }}
										{{ field }}
										{{ field.errors}}
									</div>
									{% endfor %}
								
									<!-- <div class="12u$">
										<input type="text" name="name" id="name" value="" placeholder="Name" />
									</div>
									<div class="12u$">
										<input type="text" name="name" id="name" value="" placeholder="Name" />
									</div>
									 -->

									<div class="12u$">
										<ul class="actions">
											<li><input type="submit" value="Sign Up" class="special" /></li>
											<!-- <li><input type="reset" value="Cancel" /></li> -->
										</ul>
										<ul class="actions">
											{% if document %}
												<li><a href="{% url 'create:log_in' id=document.id %}">Log In</a></li>
											{% else %}
												<li><a href="{% url 'create:log_in'%}">Log In</a></li>
											{% endif %}
										</ul>
									</div>
								</div>
							</form>
						</section>

					

				</div>
			</section>

		{% include "create/footer.html" %}

		<!-- Scripts -->
		<script src="{% static 'create/assets/js/jquery.min.js' %}"></script>
		<script src="{% static 'create/assets/js/jquery.scrolly.min.js' %}"></script>
		<script src="{% static 'create/assets/js/skel.min.js' %}"></script>
		<script src="{% static 'create/assets/js/util.js' %}"></script>
		<script src="{% static 'create/assets/js/main.js' %}"></script>
	
	</body>
</html>