create/urls.py
# create urls

from django.urls import path

from . import views

app_name = 'create'
urlpatterns = [
    path('', views.home, name='home'),
    path('my_documents', views.my_documents, name='my_documents'),
    path('create_bill_of_sale/', views.create_bill_of_sale, name='create_bill_of_sale'),
    path('create_bill_of_sale/<int:page>/', views.create_bill_of_sale, name='create_bill_of_sale'),
    path('create_bill_of_sale/<int:page>/<int:id>/', views.create_bill_of_sale, name='create_bill_of_sale'),
    path('view_bill_of_sale/', views.view_bill_of_sale, name='view_bill_of_sale'),
    path('view_bill_of_sale/<int:id>/', views.view_bill_of_sale, name='view_bill_of_sale'),
    path('view_bill_of_sale_pdf/', views.view_bill_of_sale_pdf, name='view_bill_of_sale_pdf'),
    path('view_bill_of_sale_pdf/<int:id>/', views.view_bill_of_sale_pdf, name='view_bill_of_sale_pdf'),
]

fastform/create/urls.py
# create urls

from django.urls import path

from . import views, user_views

app_name = 'create'
urlpatterns = [
    path('', views.home, name='home'),
    path('sign_up', user_views.sign_up, name='sign_up'),
    path('sign_up/<int:id>', user_views.sign_up, name='sign_up'),
    path('log_in', user_views.log_in, name='log_in'),
    path('log_in/<int:id>', user_views.log_in, name='log_in'),
    path('log_out', user_views.log_out, name='log_out'),
    path('my_documents', views.my_documents, name='my_documents'),
    path('create_document/<int:id>/', views.create_document, name='create_document'),
    path('create_bill_of_sale/', views.create_bill_of_sale, name='create_bill_of_sale'),
    path('create_bill_of_sale/<int:page>/', views.create_bill_of_sale, name='create_bill_of_sale'),
    path('create_bill_of_sale/<int:page>/<int:id>/', views.create_bill_of_sale, name='create_bill_of_sale'),
    path('view_document/<int:id>/', views.view_document, name='view_document'),
    path('view_bill_of_sale/', views.view_bill_of_sale, name='view_bill_of_sale'),
    path('view_bill_of_sale/<int:id>/', views.view_bill_of_sale, name='view_bill_of_sale'),
    path('view_pdf_document/<int:id>/', views.view_pdf_document, name='view_pdf_document'),
    path('view_pdf_bill_of_sale/', views.view_pdf_bill_of_sale, name='view_pdf_bill_of_sale'),
    path('view_pdf_bill_of_sale/<int:id>/', views.view_pdf_bill_of_sale, name='view_pdf_bill_of_sale'),
    path('delete_document/<int:id>/', views.delete_document, name='delete_document'),
]

fastform/urls.py
# Main urls
"""fastform URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('index.urls'), name='index'),
    path('create/', include('create.urls'), name='create'),
]

index/urls.py
# Index urls

from django.urls import path

from . import views

app_name = 'index'
urlpatterns = [
    path('', views.home, name='home'),
]

create/models.py
import datetime

from django.db import models
from django.utils import timezone


# Create your models here.
DOCUMENT_TYPES = (('', 'empty'), ('bill_of_sale', 'Bill of Sale'), ('articles_of_incorporation', 'Articles of Incorporation')) 

class Document(models.Model):
    doc_id = models.PositiveBigIntegerField("Document ID", default=0)
    doc_type = models.CharField("Document Type", max_length=200, blank=True, choices=DOCUMENT_TYPES, default='')
    # Document name should be Document01, 02 ... (need additional function)
    doc_name = models.CharField(max_length=20, default="Document name")
    doc_date = models.DateTimeField(default=timezone.now)

    
STATES =  (('', '- State -'), ('AL', 'Alabama'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'))

class BillOfSale(models.Model):
    # Document name should be Document01, 02 ... (need additional function)
    document_name = models.CharField(max_length=20, default="Document name")
    document_date = models.DateTimeField(default=timezone.now)

    seller_name = models.CharField('Name', max_length=200, blank=True)
    seller_address = models.CharField('Address', max_length=200, blank=True)
    seller_city = models.CharField('City', max_length=200, blank=True)
    seller_state = models.CharField("State", max_length=200, blank=True, choices=STATES, default='')
    seller_zip = models.CharField('Zip', max_length=200, blank=True)

    buyer_name = models.CharField('Name', max_length=200, blank=True)
    buyer_address = models.CharField('Address', max_length=200, blank=True)
    buyer_city = models.CharField('City', max_length=200, blank=True)
    buyer_state = models.CharField('State', max_length=200, blank=True, choices=STATES, default='')
    buyer_zip = models.CharField('Zip', max_length=5, blank=True)

    properties = models.CharField(max_length=200, blank=True)
    price = models.CharField(max_length=20, blank=True)
    sale_date = models.DateField(default=timezone.now)


    def save(self, *args, **kwargs):
        new = False
        if not self.pk:  # object is being created, thus no primary key field yet
            new = True
            
        super(BillOfSale, self).save(*args, **kwargs)
        if new:
            document = Document.objects.create()
            document.doc_id = self.id
            document.doc_type = 'bill_of_sale'
            document.doc_name = self.document_name
            document.save()

    # def __str__(self):
    #     return 

create/forms.py
from django import forms
from django.forms import ModelForm, CharField
from .models import BillOfSale
from django.utils import timezone

class BillOfSaleForm(ModelForm):
    class Meta:
        model = BillOfSale
        fields = ['seller_name', 'seller_address', 'seller_city',
        'seller_state', 'seller_zip', 'buyer_name', 'buyer_address', 'buyer_city', 'buyer_state',
        'buyer_zip', 'properties', 'price', 'sale_date']


class BillOfSaleForm01(ModelForm):
    class Meta:
        model = BillOfSale
        fields = ['seller_name', 'seller_address', 'seller_city',
        'seller_state', 'seller_zip']


class BillOfSaleForm02(ModelForm):
    class Meta:
        model = BillOfSale
        fields = ['buyer_name', 'buyer_address', 'buyer_city',
        'buyer_state', 'buyer_zip']


class BillOfSaleForm03(ModelForm):
    class Meta:
        model = BillOfSale
        fields = ['properties', 'price', 'sale_date']

    

create/views.py
from django.shortcuts import render, redirect, get_object_or_404, Http404

from django.http import HttpResponse
from django.template import loader
from django.views.decorators.clickjacking import xframe_options_sameorigin
from django.utils import timezone

from .models import BillOfSale, Document
from .forms import BillOfSaleForm, BillOfSaleForm01, BillOfSaleForm02, BillOfSaleForm03

# Create your views here.
def home(request):
    return render(request, 'create/home.html', {})


def my_documents(request):
    documents = Document.objects.all()
    return render(request, 'create/my_documents.html', {'documents': documents})


def create_bill_of_sale(request, page=None, id=None):
    instance = get_object_or_404(BillOfSale, id=id) if id else None
    next_page = 0
    if request.method == "POST":
        if page is None or page == 1:
            page = 1
            form = BillOfSaleForm01(request.POST, instance=instance)
            next_page = 2
        elif page == 2 and id:
            form = BillOfSaleForm02(request.POST, instance=instance)
            next_page = 3
        elif page == 3 and id:
            form = BillOfSaleForm03(request.POST, instance=instance)
        else:
            print("****PAGE ", page)
            raise Http404("Page does not exist")

        if form.is_valid():
            bill_of_sale = form.save()
            id = bill_of_sale.id   
        else:
            print('not valid')
            print(form.errors)
        if page == 3:    
            return redirect('create:view_bill_of_sale', id=id)    
            # return redirect('index:home')    
        return redirect('create:create_bill_of_sale', page=next_page, id=id)
    
    else:
        title = {1: "Who is the Seller?", 2: "Who is the Buyer?", 3: "What is the Property?"}
        if page is None or page == 1:
            page = 1
            form = BillOfSaleForm01(instance=instance)
        elif page == 2 and id:
            form = BillOfSaleForm02(instance=instance)
        elif page == 3 and id:
            form = BillOfSaleForm03(instance=instance)
        else:
            raise Http404("Page does not exist")
    context = {'form': form, 'page': page, "id" : id, "title" : title[page]}
    return render(request, 'create/build_bill_of_sale_01.html', context)


@xframe_options_sameorigin
def view_bill_of_sale(request, id=None):
    bill_of_sale = get_object_or_404(BillOfSale, id = id) if id else None
    template = loader.get_template('create/bill_of_sale.html')
    context = {'bill_of_sale': bill_of_sale}

    return HttpResponse(template.render(context, request))


from io import BytesIO
from django.http import HttpResponse
from django.template.loader import get_template
import xhtml2pdf.pisa as pisa

def view_bill_of_sale_pdf(request, id=None):
    bill_of_sale = get_object_or_404(BillOfSale, id = id) if id else 0
    template = loader.get_template('create/bill_of_sale_pdf.html')
    context = {'bill_of_sale': bill_of_sale}
    html = template.render(context, request)
    
    response = BytesIO()
    pdf = pisa.pisaDocument(BytesIO(html.encode("UTF-8")), response)
    if not pdf.err:
        return HttpResponse(response.getvalue(), content_type='application/pdf')
    else:
        return HttpResponse("Error Rendering PDF", status=400)

fastform/create/views.py
from django.shortcuts import render, redirect, get_object_or_404, Http404

from django.http import HttpResponse
from django.template import loader
from django.views.decorators.clickjacking import xframe_options_sameorigin
from django.utils import timezone

from .models import BillOfSale, Document
from .forms import BillOfSaleForm, BillOfSaleForm01, BillOfSaleForm02, BillOfSaleForm03

# Create your views here.
def home(request):
    return render(request, 'create/home.html', {})

def my_documents(request):
    if request.user.is_authenticated:
        user = request.user
    else:
        return redirect('create:log_in')

    documents = Document.objects.filter(user=user)
    return render(request, 'create/my_documents.html', {'documents': documents})

def create_document(request, id):
    document = get_object_or_404(Document, id=id)
    address = 'create:create_' + document.doc_type
    return redirect(address, page=1, id=document.doc_id)   

def create_bill_of_sale(request, page=None, id=None):
    instance = get_object_or_404(BillOfSale, id=id) if id else None
    next_page = 0
    if request.user.is_authenticated:
        user = request.user
    else:
        user = None
    if instance and instance.user != user:
        return redirect('create:my_documents')

    if request.method == "POST":
        if page is None or page == 1:
            page = 1
            form = BillOfSaleForm01(request.POST, instance=instance)
            next_page = 2
        elif page == 2 and id:
            form = BillOfSaleForm02(request.POST, instance=instance)
            next_page = 3
        elif page == 3 and id:
            form = BillOfSaleForm03(request.POST, instance=instance)
        else:
            print("****PAGE ", page)
            raise Http404("Page does not exist")

        if form.is_valid():
            bill_of_sale = form.save()
            id = bill_of_sale.id   
            if not instance:
                bill_of_sale.user = user
                bill_of_sale.save()
            
        else:
            print('not valid')
            print(form.errors)
        if page == 3:
            if user:    
                return redirect('create:my_documents')
            else:
                return redirect('create:log_in', id=bill_of_sale.document.id)
            # return redirect('index:home')    
        return redirect('create:create_bill_of_sale', page=next_page, id=id)
    
    else:
        title = {1: "Who is the Seller?", 2: "Who is the Buyer?", 3: "What is the Property?"}
        if page is None or page == 1:
            page = 1
            form = BillOfSaleForm01(instance=instance)
        elif page == 2 and id:
            form = BillOfSaleForm02(instance=instance)
        elif page == 3 and id:
            form = BillOfSaleForm03(instance=instance)
        else:
            raise Http404("Page does not exist")
    context = {'form': form, 'page': page, "id" : id, "title" : title[page]}
    return render(request, 'create/build_bill_of_sale_01.html', context)

def view_document(request, id):
    document = get_object_or_404(Document, id=id)
    address = 'create:view_' + document.doc_type
    return redirect(address, id=document.doc_id)   


@xframe_options_sameorigin
def view_bill_of_sale(request, id=None):
    bill_of_sale = get_object_or_404(BillOfSale, id = id) if id else None
    template = loader.get_template('create/bill_of_sale.html')
    context = {'bill_of_sale': bill_of_sale}

    return HttpResponse(template.render(context, request))


def view_pdf_document(request, id):
    document = get_object_or_404(Document, id=id)
    address = 'create:view_pdf_' + document.doc_type
    return redirect(address, id=document.doc_id)   


from io import BytesIO
from django.http import HttpResponse
from django.template.loader import get_template
import xhtml2pdf.pisa as pisa

def view_pdf_bill_of_sale(request, id=None):
    bill_of_sale = get_object_or_404(BillOfSale, id = id) if id else 0
    template = loader.get_template('create/bill_of_sale_pdf.html')
    context = {'bill_of_sale': bill_of_sale}
    html = template.render(context, request)
    
    response = BytesIO()
    pdf = pisa.pisaDocument(BytesIO(html.encode("UTF-8")), response)
    if not pdf.err:
        return HttpResponse(response.getvalue(), content_type='application/pdf')
    else:
        return HttpResponse("Error Rendering PDF", status=400)

document_models = {"bill_of_sale": BillOfSale}
def delete_document(request, id):
    document = get_object_or_404(Document, id=id)
    document_child = get_object_or_404(document_models[document.doc_type], id=document.doc_id)
    document_child.delete()
    document.delete()
    return redirect('create:my_documents')

create/templates/create/bill_of_sale.html
<html>
  <head>
    <title></title>
    <meta content="">
    <style>
      div{
        background-color:white;
        text-align:justify;
      }
      .no-justify{
        text-align: left;
      }

      /* span{
        background-color:white;
        width:100%;
        height:1em;
        display:inline-block;
      } */
      body{padding: 50px;text-overflow:clip;}p{margin-bottom: 5px;}.page-break{display:block; margin-bottom: 75px; padding-bottom: 75px; border-bottom: 1px dashed #999;}@media (max-width: 480px) {body{padding: 10px;overflow-wrap: break-word;hyphens: auto;word-break: break-word;}}

    /* Style the empty variables */
    .empty-var{
        display: inline-block;
        width: 200px;
        border-bottom: 1px solid #999;
        height: 20px;
        background: #e2e2e2;
    }
    </style>
  </head>
  <body>
    <h2 style="text-align: center;">Bill of Sale</h2>
    <div>
    <p>
      THIS BILL OF SALE is executed on {{ bill_of_sale.sale_date }}, by and 
      between {% if bill_of_sale.seller_name %}{{ bill_of_sale.seller_name }}{% else %}<span class="empty-var"> </span>{% endif %}, residing at 
      {% if bill_of_sale.seller_address %}{{ bill_of_sale.seller_address }}{% else %}<span class="empty-var"> </span>{% endif %} {% if bill_of_sale.seller_city %}{{ bill_of_sale.seller_city }}{% else %}<span class="empty-var"> </span>{% endif %}, 
      {% if bill_of_sale.seller_state %}{{ bill_of_sale.seller_state }}{% else %}<span class="empty-var"> </span>{% endif %} {% if bill_of_sale.seller_zip %}{{ bill_of_sale.seller_zip }}{% else %}<span class="empty-var"> </span>{% endif %} 
       (hereinafter referred to as the "Seller") and 
       {% if bill_of_sale.buyer_name %}{{ bill_of_sale.buyer_name }}{% else %}<span class="empty-var"> </span>{% endif %}, residing at 
       {% if bill_of_sale.buyer_address %}{{ bill_of_sale.buyer_address }}{% else %}<span class="empty-var"> </span>{% endif %} {% if bill_of_sale.buyer_city %}{{ bill_of_sale.buyer_city }}{% else %}<span class="empty-var"> </span>{% endif %}, 
       {% if bill_of_sale.buyer_state %}{{ bill_of_sale.buyer_state }}{% else %}<span class="empty-var"> </span>{% endif %} {% if bill_of_sale.buyer_zip %}{{ bill_of_sale.buyer_zip }}{% else %}<span class="empty-var"> </span>{% endif %}
       (hereinafter referred to as the "Buyer").
       <span></span>
    </p>
    <p>
      Seller hereby agrees to transfers to Buyer all rights of Seller in 
      the following property:
    </p>
    <p>
      {% if bill_of_sale.properties %}{{ bill_of_sale.properties }}{% else %}<span class="empty-var"> </span>{% endif %}
    </p>
    <p>
      For and in consideration of a total purchase price of ${% if bill_of_sale.price %}{{ bill_of_sale.price }}{% else %}0.00{% endif %}, receipt of
      which is hereby acknowledged by Seller. The form of payment used will be
       cash and sales tax is included in the purchase price of the above-mentioned property.

    </p>
    <p>
      The transfer of property shall take effect immediately upon execution of
       this Bill of Sale by both parties. Upon signing this Bill of Sale, the 
       above-mentioned property shall belong exclusively to the Buyer, and the
        Seller shall have no further responsibility for, liability towards or 
        interest in, said property.
    </p>
    <p>
      The Seller hereby affirms that the above information about this property
       is accurate to the best of his/her knowledge, and by his/her signature 
       below certifies s/he is the lawful owner of the property with the ability
        to sell it as s/he sees fit.
    </p>
    <p>
      The sale and transfer of property is hereby made on an "AS IS" condition,
       without any express or implied warranties, with no recourse to the Seller,
        provided that Seller can issue proof that it has title to the property 
        without any liens or encumbrances. The Buyer has been given the opportunity 
        to inspect, or has inspected, the property as described above. The Buyer agrees 
        to accept all property in its existing state.
    </p>
    <p>
      IN WITNESS THEREOF, the parties executed this Bill of Sale on {{ bill_of_sale.sale_date }},
    </p>
    <div class="no-justify">
      <br>
      <br>
      <br>
      <br>
      <br>
      
      (Signature of Buyer)  (Date)
      <br>
      {% if bill_of_sale.buyer_name %}{{ bill_of_sale.buyer_name }}{% else %}<span class="empty-var"> </span>{% endif %}<br>
      {% if bill_of_sale.buyer_address %}{{ bill_of_sale.buyer_address }}{% else %}<span class="empty-var"> </span>{% endif %}<br>
      {% if bill_of_sale.buyer_city %}{{ bill_of_sale.buyer_city }}{% else %}<span class="empty-var"> </span>{% endif %}, {% if bill_of_sale.buyer_state %}{{ bill_of_sale.buyer_state }}{% else %}<span class="empty-var"> </span>{% endif %} {% if bill_of_sale.buyer_zip %}{{ bill_of_sale.buyer_zip }}{% else %}<span class="empty-var"> </span>{% endif %}<br>
       
      <br>
      <br>
      <br>
      <br>
      <br>
      
      (Signature of Seller)  (Date)
      <br>
      {% if bill_of_sale.seller_name %}{{ bill_of_sale.seller_name }}{% else %}<span class="empty-var"> </span>{% endif %}<br> 
      {% if bill_of_sale.seller_address %}{{ bill_of_sale.seller_address }}{% else %}<span class="empty-var"> </span>{% endif %}<br>
      {% if bill_of_sale.seller_city %}{{ bill_of_sale.seller_city }}{% else %}<span class="empty-var"> </span>{% endif %}, {% if bill_of_sale.seller_state %}{{ bill_of_sale.seller_state }}{% else %}<span class="empty-var"> </span>{% endif %} {% if bill_of_sale.seller_zip %}{{ bill_of_sale.seller_zip }}{% else %}<span class="empty-var"> </span>{% endif %}<br> 
      
    </div>
  </div>
  </body>
</html>

create/templates/create/home.html
{% load static %}

<!DOCTYPE HTML>

<html>
	<head>
		<title>FastForm - Create your form</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" type="text/css" href="{% static 'create/assets/css/main.css'%}" />
	</head>
	<body>

		<!-- Header -->
		<header id="header">
			<a href="index.html" class="logo"><strong>FastForm</strong></a>
			<nav>
				<a href="#menu">Menu</a>
			</nav>
		</header>

	<!-- Nav -->
		<nav id="menu">
			<ul class="links">
				<li><a href="index.html">Home</a></li>
				<li><a href="my_account.html">My Account</a></li>
				<li><a href="log_in.html">Log In</a></li>
			</ul>
		</nav>
		<!-- Main -->
			<section id="main">
				<div class="inner">
					<header class="major special">
						<h1>Free Legal Documents</h1>
						<p>A tool from the document experts at FastForm</p>
					</header>

					<!-- Text -->
						<section>
							
							<header>
								
								<h2>Financial</h2>
							</header>

							<header>
								<a href="{% url 'create:create_bill_of_sale'  %}" class="logo"><h4>Bill Of Sale</h4></a>
							</header>
							<p>Nunc lacinia ante nunc ac lobortis. Interdum adipiscing gravida odio porttitor sem non mi integer non faucibus ornare mi ut ante amet placerat aliquet. Volutpat eu sed ante lacinia sapien lorem accumsan varius montes viverra nibh in adipiscing blandit tempus accumsan.
								<ul class="actions">
									<li><a href="{% url 'create:create_bill_of_sale' %}" class="button special">Create New</a></li>
									<li><a href="#" class="button icon fa-download">Download Word File</a></li>
									<li><a href="{% url 'create:view_bill_of_sale_pdf' %}" class="button icon fa-download">Download PDF</a></li>
								</ul>
							</p>
							
							<header>
								<h4>Cease And Desist Breach Of Contract Letter</h4>
							</header>
							<p>Nunc lacinia ante nunc ac lobortis. Interdum adipiscing gravida odio porttitor sem non mi integer non faucibus ornare mi ut ante amet placerat aliquet. Volutpat eu sed ante lacinia sapien lorem accumsan varius montes viverra nibh in adipiscing blandit tempus accumsan.
								<ul class="actions">
									<li><a href="#" class="button special">Edit PDF</a></li>
									<li><a href="#" class="button">Download Word File</a></li>
									<li><a href="#" class="button alt">Download PDF</a></li>
								</ul>
							</p>
							
							<hr />

							<h2>Bussiness</h2>
						</header>

						<header>
							<h4>Articles Of Incorporation</h4>
						</header>
						<p>Nunc lacinia ante nunc ac lobortis. Interdum adipiscing gravida odio porttitor sem non mi integer non faucibus ornare mi ut ante amet placerat aliquet. Volutpat eu sed ante lacinia sapien lorem accumsan varius montes viverra nibh in adipiscing blandit tempus accumsan.</p>
						
						<header>
							<h4>Bill Of Lading</h4>
						</header>
						<p>Nunc lacinia ante nunc ac lobortis. Interdum adipiscing gravida odio porttitor sem non mi integer non faucibus ornare mi ut ante amet placerat aliquet. Volutpat eu sed ante lacinia sapien lorem accumsan varius montes viverra nibh in adipiscing blandit tempus accumsan.</p>
						
						<hr />

				</div>
			</section>

		<!-- Footer -->
			<footer id="footer">
				<ul class="icons">
					<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
					<li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
					<li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
				</ul>
				<div class="copyright">
					&copy; Untitled. Design: <a href="https://templated.co">TEMPLATED</a>. Images: <a href="https://unsplash.com">Unsplash</a>.
				</div>
			</footer>

		<!-- Scripts -->
			<!-- Scripts -->
			<script src="{% static 'create/assets/js/jquery.min.js' %}"></script>
			<script src="{% static 'create/assets/js/jquery.scrolly.min.js' %}"></script>
			<script src="{% static 'create/assets/js/skel.min.js' %}"></script>
			<script src="{% static 'create/assets/js/util.js' %}"></script>
			<script src="{% static 'create/assets/js/main.js' %}"></script>
		

	</body>
</html>